In [1]:
import torch

In [2]:
torch.tensor([[1., -1],[1., -1]])

tensor([[ 1., -1.],
        [ 1., -1.]])

In [6]:
print(torch.tensor([[1,2], [3,4]]))
print(torch.tensor([[1,2],[3,4]], device="mps"))
print(torch.tensor([[1,2],[3,4]], dtype=torch.float32))

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], device='mps:0')
tensor([[1., 2.],
        [3., 4.]])


In [7]:
temp = torch.tensor([[1,2],[3,4]])
print(temp.numpy())

temp = torch.tensor([[1,2],[3,4]], device= "mps")
print(temp.to("cpu").numpy())

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [9]:
temp =torch.FloatTensor([1,2,3,4,5,6,7])
print(temp[0], temp[1], temp[-1])
print(temp[2:5], temp[4 : -1])

tensor(1.) tensor(2.) tensor(7.)
tensor([3., 4., 5.]) tensor([5., 6.])


In [10]:
v= torch.tensor([1,2,3])
w= torch.tensor([3,4,6])
print(w - v)

tensor([2, 2, 3])


In [11]:
temp = torch.tensor([[1,2],[3,4]])

In [18]:
import pandas as pd
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
#data = pd.read_csv('./car_evaluation.csv')

In [19]:
#$class CustomDataset(Dataset):
#    def __init__(self, csv.file):
#        self.label = pd.read_csv(csv_file)

In [ ]:
import torchvision.transforms as transforms
from torchvision.datasets import MNIST
import requests


In [30]:
mnist_transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (1.0,))
])
download_root = '/Users/t08/works/deep_advance/data/MNIST_DATASET'
train_dataset = MNIST(download_root, transform= mnist_transform, train =True, download=True)
valid_dataset = MNIST(download_root, transform= mnist_transform, train=False, download= True)
test_dataset = MNIST(download_root,transform=mnist_transform, train =False, download= True)

100.0%
100.0%
100.0%
100.0%


In [34]:
import torch.nn as nn
class MLP(nn.Module):
    def __init__(self):
        super(MLP , self).__init__()
        self.layer1 = nn.Sequential(
            nn.Conv2d(in_channels=3, out_channels = 64, kernel_size = 5),
            nn.ReLU(inplace = True),
            nn.MaxPool2d(2)
        )
        self.layer2 = nn.Sequential(
            nn.Conv2d(in_channels=64, out_channels = 30, kernel_size = 5),
            nn.ReLU(inplace = True),
            nn.MaxPool2d(2)
        )
        self.layer1 = nn.Sequential(
            nn.Linear(in_features =30*5*5, out_features = 10, bias = True),
            nn.ReLU(inplace = True),
        )

        def forward(self, x):
            x= self.layer1(x)
            x= self.layer2(x)
            x= x.view(x.shape[0], -1)
            x = self.layer3(x)
            return x

model = MLP()


In [35]:
print("printing children\n")
print(list(model.children()))
print("\n\nprinting Modules\n")
print(list(model.modules()))

printing children

[Sequential(
  (0): Linear(in_features=750, out_features=10, bias=True)
  (1): ReLU(inplace=True)
), Sequential(
  (0): Conv2d(64, 30, kernel_size=(5, 5), stride=(1, 1))
  (1): ReLU(inplace=True)
  (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
)]


printing Modules

[MLP(
  (layer1): Sequential(
    (0): Linear(in_features=750, out_features=10, bias=True)
    (1): ReLU(inplace=True)
  )
  (layer2): Sequential(
    (0): Conv2d(64, 30, kernel_size=(5, 5), stride=(1, 1))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
), Sequential(
  (0): Linear(in_features=750, out_features=10, bias=True)
  (1): ReLU(inplace=True)
), Linear(in_features=750, out_features=10, bias=True), ReLU(inplace=True), Sequential(
  (0): Conv2d(64, 30, kernel_size=(5, 5), stride=(1, 1))
  (1): ReLU(inplace=True)
  (2): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
), Co